[env:esp32p4_pioarduino]
platform = https://github.com/pioarduino/platform-espressif32.git#54.03.21
upload_speed = 1500000
monitor_speed = 115200
build_type = debug
framework = arduino
board = esp32-p4-evboard

; Hardware-spezifische Settings
board_build.mcu = esp32p4
board_build.flash_mode = qio

build_flags = 
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=5
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	
	; LVGL Configuration Flags (ersetzt lv_conf.h)
	-DLV_CONF_SKIP
	-DLV_COLOR_DEPTH=16
	-DLV_TICK_CUSTOM=1
	-DLV_USE_PERF_MONITOR=1    ; Zeigt FPS und CPU Last auf dem Display an
	-DLV_FONT_MONTSERRAT_24=1  ; Größere Schrift laden für das 720p Display

lib_deps = 
	https://github.com/M5Stack/M5Unified.git
	https://github.com/M5Stack/M5GFX.git
	lvgl/lvgl@^8.3.11 ; Version 8.x ist stabilsten im Zusammenspiel mit M5GFX
